# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fb4724d2b1710abb66be5a19267242d71ec3be456fd5a03df13787239c8b531ef7a95dfa543fc324df226db0f4991b0835e56b85a2828e35363c566f40ff748

test:
  secret_key_base: c62b0cc676e1be453a5abd6e3961fb43f39a4fd089f9598bceb846b7946d929722b8355abd79eaf5ac146a04bf6c5565460fdd2d0062f8b44fe8497d3ea30378

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
